openapi: 3.0.0
info:
    version: "1"
    title: "LongTask"
    description: Manifest description
servers:
    - url: http://server-host/openapi/Articles/v1
paths:
    "/articles":
        post:
            tags:
                - Articles
            operationId: createArticle
            summary: "Create an article"
            requestBody:
                required: true
                content:
                    application/vnd.rollun-request+json:
                        schema:
                            $ref: '#/components/schemas/ArticlePostRequest'
            responses:
                "200":
                    description: "Article successfully created"
                    content:
                        application/vnd.rollun+json:
                            schema:
                                $ref: '#/components/schemas/ArticleResult'
                "202":
                    description: "Article creation pending"
                    headers:
                        Retry-After:
                            schema:
                                type: integer
                            description: Task duration estimate
                    content:
                        application/vnd.rollun-long-task+json:
                            schema:
                                $ref: '#/components/schemas/ArticleLongTaskResult'
                "500":
                    description: 'Some internal error'
                    content:
                        application/vnd.rollun-error+json:
                            schema:
                                $ref: "https://raw.githubusercontent.com/misha-rollun/openapi-common/master/src/openapi/common/v1/common-v1.yaml#/components/schemas/Error"
    "/articles/{id}":
        get:
            tags:
                - Articles
            operationId: getArticle
            summary: 'Get info about specific article'
            description: "Returns information of article by id"
            parameters:
                - in: path
                  name: id
                  description: Id of article
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: 'Success'
                    content:
                        application/vnd.rollun+json:
                            schema:
                                $ref: '#/components/schemas/ArticleResult'
                "500":
                    description: 'Some internal error'
                    content:
                        application/vnd.rollun-error+json:
                            schema:
                                $ref: "https://raw.githubusercontent.com/misha-rollun/openapi-common/master/src/openapi/common/v1/common-v1.yaml#/components/schemas/Error"
    "/articles/actions/post/{id}":
        get:
            tags:
                - Articles
            operationId: getArticlePostTask
            summary: 'Get info about article creation task'
            parameters:
                -   in: path
                    name: id
                    description: Id of task
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: 'Success'
                    content:
                        application/vnd.rollun-long-task+json:
                            schema:
                                $ref: '#/components/schemas/ArticleLongTaskResult'
                "303":
                    description: "Task completed"
                    content:
                        application/vnd.rollun-long-task+json:
                            schema:
                                $ref: '#/components/schemas/ArticleCompletedLongTaskResult'
                "500":
                    description: 'Some internal error'
                    content:
                        application/vnd.rollun-error+json:
                            schema:
                                $ref: "https://raw.githubusercontent.com/misha-rollun/openapi-common/master/src/openapi/common/v1/common-v1.yaml#/components/schemas/Error"
components:
    schemas:
        ArticleCompletedLongTaskResult:
            type: object
            properties:
                task:
                    $ref: '#/components/schemas/ArticleCompletedLongTask'
        ArticleLongTaskResult:
            type: object
            properties:
                task:
                    $ref: '#/components/schemas/ArticleLongTask'
        ArticleCompletedLongTask:
            allOf:
                - $ref: '#/components/schemas/CompletedLongTask'
            type: object
        ArticleLongTask:
          allOf:
            - $ref: '#/components/schemas/LongTask'
          type: object

        CompletedLongTask:
            allOf:
                - $ref: '#/components/schemas/LongTask'
            type: object
            required:
                - result
            properties:
                result:
                    type: string
        LongTask:
          type: object
          required:
              - id
          properties:
            id:
              type: string


        ## One resource result
        ArticleResult:
            allOf:
                - $ref: "https://raw.githubusercontent.com/misha-rollun/openapi-common/master/src/openapi/common/v1/common-v1.yaml#/components/schemas/RollunResponse"
            properties:
                data:
                    $ref: '#/components/schemas/Article'

        ## Body for post request
        ArticlePostRequest:
            type: object
            required:
                - payload
            properties:
                payload:
                    $ref: "#/components/schemas/ArticlePostRequestPayload"
        ArticlePostRequestPayload:
            type: object
            required:
                - title
            properties:
                title:
                    type: string

        ## Resource object
        Article:
            type: object
            properties:
                id:
                    type: string
                title:
                    type: string
