services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm
  php-fpm:
    image: maxrollundev/php-fpm-8.0
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
